homeassistant:
  customize: !include includes/customization.yaml
  packages: !include_dir_merge_named includes/packages


lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml

frontend:
  themes: !include_dir_merge_named themes

# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

toiletlid:
  - platform: xjx_toilet_pro
    host: 192.168.31.22
    token: !secret xjx_toilet_pro_token
    name: 'Xiaomi Whale Smart Toilet Cover'