homeassistant:
  customize: !include includes/customization.yaml
  packages: !include_dir_merge_named includes/packages


lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml


# Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
